import { Component, OnInit } from '@angular/core';
import { ApexOptions, NgApexchartsModule } from 'ng-apexcharts';
import { SharedModule } from 'src/app/theme/shared/shared.module';
import { DeviceClient, DeviceOrderedMeasureRangeResponse, DeviceResponse, MeasureClient, OrderedMeasureResponse } from 'src/app/generated/autogenerated-client';
import { LineChartComponent, LineChartData } from "../charts/line-chart/line-chart.component";

@Component({
  selector: 'app-single-device-chart',
  templateUrl: './single-device-chart.component.html',
  styleUrls: ['./single-device-chart.component.scss'],
  imports: [NgApexchartsModule, SharedModule, LineChartComponent],
  providers: [DeviceClient, MeasureClient],
  standalone: true
})

export class DeviceChartComponent implements OnInit {
  devices: DeviceResponse[] = [];
  chartData: LineChartData[] = [];
  availableMeasureTypes: string[] = [];
  measureTypeValue: string = 'temperature';
  selectedDeviceId: string = '';
  timespan: string = '24h';
  chartOptions: Partial<ApexOptions> = {};

  constructor(
    private readonly deviceClient:DeviceClient,
    private readonly measureClient:MeasureClient
  ) {}

  ngOnInit(): void {
    this.fetchDevices();
  }

  fetchDevices() {
    this.deviceClient.getAllDevices().subscribe(data => {
      this.devices = data;

      if (this.devices.length > 0) {
        this.selectedDeviceId = this.devices[0].id!;
        this.measureTypeValue = 'temperature';
      }
    })
  }

  onDeviceChange():void {
    if (this.selectedDeviceId) {
      this.fetchDeviceMeasureTypes();
      this.fetchDeviceData();
    }
  }

  onMeasureTypeChange():void{
    this.fetchDeviceData();
  }

  onTimespanChange():void{
    if (this.selectedDeviceId) {
      this.fetchDeviceData();
    }
  }

  fetchDeviceMeasureTypes(){
    this.deviceClient.getAvailableMeasuresByDeviceId(this.selectedDeviceId).subscribe(response => {
      this.availableMeasureTypes = response.measureTypes ?? [];

      if (this.availableMeasureTypes.length > 0) {
        this.measureTypeValue = this.availableMeasureTypes[0];
      }
    })
  }

  fetchDeviceData() {
    let endDate = new Date();
    let startDate = this.subtractTime(endDate, this.timespan);

    this.measureClient.getMeasuresByDeviceIdAndDate(this.selectedDeviceId, startDate, endDate).subscribe(response => {
      console.log(response);
      let some = this.groupMeasurementsByType(response.measures!)
      console.log(some);
      this.chartData = some;
    })
  }

  groupMeasurementsByType(measurements: OrderedMeasureResponse[]):LineChartData[] {
    const grouped: { [key: string]: { x: Date; y: number }[] } = {};

    for (const m of measurements) {
      if (!grouped[m.type!]) {
        grouped[m.type!] = [];
      }
      grouped[m.type!].push({ x: m.created!, y: m.dataValue! });
    }

    return Object.keys(grouped).map(type => ({
      name: type,
      data: grouped[type]
    })) as LineChartData[];
  }


  subtractTime(date: Date, duration: string): Date {
    const regex = /^(\d+)([smhdw])$/; // supports seconds, minutes, hours, days, weeks
    const match = duration.match(regex);

    if (!match) {
      throw new Error("Invalid duration format. Use formats like '15m', '2h', '3d', etc.");
    }

    const value = parseInt(match[1], 10);
    const unit = match[2];

    let milliseconds = 0;

    switch (unit) {
      case 's': milliseconds = value * 1000; break;
      case 'm': milliseconds = value * 60 * 1000; break;
      case 'h': milliseconds = value * 60 * 60 * 1000; break;
      case 'd': milliseconds = value * 24 * 60 * 60 * 1000; break;
      case 'w': milliseconds = value * 7 * 24 * 60 * 60 * 1000; break;
      default: throw new Error("Unsupported time unit.");
    }

    return new Date(date.getTime() - milliseconds);
  }

}
