import { Injectable } from "@angular/core";
import { DeviceClient, DeviceCollectionResponse, DeviceResponse } from "../generated/autogenerated-client";
import { firstValueFrom, Observable } from "rxjs";

@Injectable({
  providedIn: 'root',
})

export class DeviceLookupService {

  private internalDeviceCache:DeviceResponse[] | undefined;

  constructor(private readonly deviceClient:DeviceClient) { }

  getAllDevicesAsync():Observable<DeviceCollectionResponse> {
    var call = this.deviceClient.getAllDevices();

    call.subscribe(data => {
      this.internalDeviceCache = data.devices ?? [];
    });

    return call;
  }

  async getAllDevicesCached():DeviceResponse[] {

    if(this.internalDeviceCache == undefined){
      var allData = await firstValueFrom(this.deviceClient.getAllDevices());
      this.internalDeviceCache = allData.devices ?? [];
      return this.internalDeviceCache;
    } else {
      return this.internalDeviceCache;
    }
  }

  getDeviceName(deviceId: string): string {
    return `Device-${deviceId}`;
  }
}