import { Component, OnInit } from "@angular/core";
import { NgApexchartsModule } from "ng-apexcharts";
import { Subject } from "rxjs";
import { LineChartComponent, LineChartData } from "src/app/components/charts/line-chart/line-chart.component";
import { DateTimeComponent } from "src/app/components/date-time/date-time.component";
import { DeviceClient, MeasureClient } from "src/app/generated/autogenerated-client";
import { SharedModule } from "src/app/theme/shared/shared.module";

@Component({
  selector: 'app-all-device-data-view',
  templateUrl: './all-device-data-view.component.html',
  styleUrls: ['./all-device-data-view.component.scss'],
  imports: [NgApexchartsModule, SharedModule, LineChartComponent, DateTimeComponent],
  providers: [DeviceClient, MeasureClient],
  standalone: true
})

export class AllDeviceDataView implements OnInit {

  deviceData$:Subject<LineChartData[]>;
  startDate: Date = new Date();
  endDate: Date = new Date();

  constructor(){
    this.deviceData$ = new Subject<LineChartData[]>();
    this.startDate = new Date(this.endDate.getTime() - 24 * 60 * 60 * 1000);
  }

  ngOnInit(): void {

  }

  onDateChange(date:Date):void{
    //
  }
}