- name: Pull images
  hosts: localhost
  become: true
  vars:
    client_id_secret: "{{ clientid }}"
    password_secret: "{{ secret }}"
    tenant_id: "{{ tenantid }}"
  
  tasks:
    - name: Configure Runner identity
      ansible.builtin.include_tasks: ../tasks/configure_identity.yml