- name: Ensure the directory exists
  ansible.builtin.file:
    path: /home/homeautomation
    state: directory
    mode: '0755'

- name: Ensure the directory exists
  ansible.builtin.file:
    path: /home/homeautomation/logs
    state: directory
    mode: '0755'

- name: Copy service file to destination
  ansible.builtin.copy:
    src: ../files/homeautomation.service
    dest: /lib/systemd/system

- name: Template identity file
  ansible.builtin.template:
    src: ../templates/docker-compose.yml.j2
    dest: /home/homeautomation/docker-compose.yml

- name: Reread configurations
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Check if the service exists
  shell: systemctl status homeautomation.service
  register: service_check
  ignore_errors: true
  changed_when: false
  no_log: true

- name: Stop service homeautomation
  ansible.builtin.service:
    name: homeautomation
    state: stopped
  when: service_check.rc == 0

- name: Enable service homeautomation
  ansible.builtin.service:
    name: homeautomation
    enabled: yes

- name: Start homeautomation
  ansible.builtin.service:
    name: homeautomation
    state: started