- name: Ensure the directory exists
  ansible.builtin.file:
    path: /home/homeautomation
    state: directory
    mode: '0755'

- name: Ensure the directory exists
  ansible.builtin.file:
    path: /home/homeautomation/logs
    state: directory
    mode: '0755'

- name: Copy service file to destination
  ansible.builtin.copy:
    src: ../files/homeautomation.service
    dest: /lib/systemd/system

- name: Fetch secret from Azure Key Vault
  azure.azcollection.azure_rm_keyvaultsecret_info:
    name: "application-insights-connection-string"
    vault_uri: "https://tgckvhadev.vault.azure.net/"
  register: fetched_secret
  #no_log: true

- name: Template docker-compose file
  ansible.builtin.template:
    src: ../templates/docker-compose.yml.j2
    dest: /home/homeautomation/docker-compose.yml
  vars:
      ai_connectionstring: "{{ fetched_secret.value }}"

- name: Reread configurations
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Check if the service exists
  shell: systemctl status homeautomation.service
  register: service_check
  ignore_errors: true
  changed_when: false
  no_log: true

- name: Stop service homeautomation
  ansible.builtin.service:
    name: homeautomation
    state: stopped
  when: service_check.rc == 0

- name: Enable service homeautomation
  ansible.builtin.service:
    name: homeautomation
    enabled: yes

- name: Start homeautomation
  ansible.builtin.service:
    name: homeautomation
    state: started