- name: Ensure the directory exists
  ansible.builtin.file:
    path: /home/homeautomation/identity
    state: directory
    mode: '0755'

- name: Template identity file
  ansible.builtin.template:
    src: ../templates/identity_file.txt.j2
    dest: /home/homeautomation/identity/identity_file.txt