
- name: Get installed Azure CLI version
  shell: az version --query '"azure-cli"' -o tsv
  register: az_installed_version
  changed_when: false

- name: Prefix Azure CLI version with a component name
  set_fact:
    az_version_prefixed: "azure-cli-{{ az_installed_version.stdout }}"

- name: Get latest Azure CLI version from GitHub
  uri:
    url: "https://api.github.com/repos/Azure/azure-cli/releases/latest"
    return_content: yes
  register: github_release

- name: Parse latest version from GitHub response
  set_fact:
    az_latest_version: "{{ github_release.json.tag_name }}"

- name: Compare versions and set update_needed
  set_fact:
    update_needed: "{{ az_version_prefixed != az_latest_version }}"

- name: Debug version info
  debug:
    msg: |
      Installed:     {{ az_version_prefixed }}
      Latest:        {{ az_latest_version }}
      Update needed: {{ update_needed }}

- name: Run this task only if Azure CLI is outdated
  debug:
    msg: "Azure CLI is outdated. Proceeding with update or next steps..."
  when: update_needed

- name: Install AZ CLI
  shell: |
    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  when: update_needed

