// angular import
import { Component } from '@angular/core';

// project import
import { SharedModule } from 'src/app/theme/shared/shared.module';

import { DeviceClient, DeviceResponse } from 'src/app/generated/autogenerated-client';
import { DeviceTableComponent } from "../../components/device-table/device-table.component";
@Component({
  selector: 'app-devices',
  standalone: true,
  imports: [SharedModule, DeviceTableComponent],
  providers: [DeviceClient],
  templateUrl: './devices.component.html',
  styleUrls: ['./devices.component.scss']
})
export default class DevicesComponent {

  // constructor
  constructor(private deviceClient:DeviceClient) {
  }

  ngOnInit() {

  }
}
