
import { Component, Input } from '@angular/core';
import { ApexOptions, NgApexchartsModule } from 'ng-apexcharts';
import { MeasureClient } from 'src/app/generated/autogenerated-client';
import { SharedModule } from 'src/app/theme/shared/shared.module';

@Component({
  selector: 'app-line-chart',
  standalone: true,
  imports: [NgApexchartsModule, SharedModule],
  providers: [MeasureClient],
  templateUrl: './line-chart.component.html',
  styleUrl: './line-chart.component.scss'
})

export class LineChartComponent {

  @Input('chartData') chartData: LineChartData[] = [];

  summaryChart: ApexOptions = {
    chart: {
      height: 350,
      type: 'area'
    },
    dataLabels: {
      enabled: false
    },
    series: this.chartData,
    stroke: {
      curve: 'smooth'
    },
    xaxis: {
      type: 'datetime',
      labels: {
        formatter: function (value: string) {
          const date = new Date(value);
          return date.toUTCString(); // e.g., "11/05/2025"
        }
      }
    },
    yaxis: {
      labels: {
        formatter: (val: number) => val.toFixed(0) // 1 decimal place
      }
    },
    tooltip: {
      x: {
        format: 'dd/MM/yy HH:mm'
      },
      y: {
        formatter: (val: number) => val.toFixed(1) // 1 decimal place
      }
    }
  };
}

export type LineChartData = {
  name:string
  data:any
}