import { Component } from '@angular/core';
import { ApiKeyRequest, DeviceClient, DeviceResponse, MeasureClient } from 'src/app/generated/autogenerated-client';
import { SharedModule } from 'src/app/theme/shared/shared.module';
import { DynamicPopupComponent } from '../dynamic-popup/dynamic-popup.component';
import { MatDialog } from '@angular/material/dialog';

@Component({
  selector: 'app-device-table',
  imports: [SharedModule, DynamicPopupComponent],
  providers: [DeviceClient, MeasureClient],
  standalone: true,
  templateUrl: './device-table.component.html',
  styleUrl: './device-table.component.scss'
})
export class DeviceTableComponent {

  deviceData: DeviceResponse[] = [];
  isPopupVisible = false;

  constructor(private deviceClient: DeviceClient, private measureClient: MeasureClient) {

  }

  ngOnInit() {
    this.loadDevices();
  }

  loadDevices() {
    this.deviceClient.getAllDevices().subscribe(data => {
      this.deviceData = data;
    })
  }

  showPopup() {
	  this.isPopupVisible = true;
  }

  hidePopup() {
	  this.isPopupVisible = false;
  }

  generateNewApiKey(id: string) {

    var apiKeyRequest = new ApiKeyRequest();
    apiKeyRequest.expirationDate = new Date();
    apiKeyRequest.name = "SomeName"

    this.deviceClient.updateApiKey(id, apiKeyRequest).subscribe(response => {
      console.log(response)
    })
  }

  getLatestOrderedMeasuresForDevice(id: string) {
    this.measureClient.getLatestActivityByDeviceId(id).subscribe(response => {
      console.log(response);
    });
  }

  deleteDevice(id: string) {
    this.deviceClient.deleteDevice(id).subscribe(data => {
      this.loadDevices();
    })
  }
}
