import { Component } from '@angular/core';
import { ApiKeyRequest, DeviceClient, DeviceResponse, MeasureClient, MeasureRangeResponse } from 'src/app/generated/autogenerated-client';
import { SharedModule } from 'src/app/theme/shared/shared.module';
import { DynamicPopupComponent } from '../dynamic-popup/dynamic-popup.component';
import { DynamicModalComponent } from "../dynamic-modal/dynamic-modal.component";
import { FormControl, FormGroup } from '@angular/forms';

@Component({
  selector: 'app-device-table',
  imports: [SharedModule, DynamicModalComponent],
  providers: [DeviceClient, MeasureClient],
  standalone: true,
  templateUrl: './device-table.component.html',
  styleUrl: './device-table.component.scss'
})
export class DeviceTableComponent {

  deviceData: DeviceResponse[] = [];
  specificDeviceActivity:MeasureRangeResponse = {} as MeasureRangeResponse;

  apiResponse: any;

  isUpdateApiKeyModalVisible: boolean = false;
  isLatestActivityModalVisible: boolean = false;

  formData: FormGroup<ApiKeyFormControls> = new FormGroup<ApiKeyFormControls>({
    name: new FormControl('', []),
    expirationDays: new FormControl(30, [])
  });

  private deviceId:string = "";

  constructor(private deviceClient: DeviceClient, private measureClient: MeasureClient) {

  }

  ngOnInit() {
    this.loadDevices();
  }

  loadDevices() {
    this.deviceClient.getAllDevices().subscribe(data => {
      this.deviceData = data.devices ?? [];
    })
  }

  onModalClose() {
    this.apiResponse = null;
    this.isUpdateApiKeyModalVisible = false;
    this.isLatestActivityModalVisible = false;
  }

  openGenerateApiKeyModal(id: string){
    this.isUpdateApiKeyModalVisible = true;
    this.deviceId = id;
  }

  openLatestActivityModal(id: string){
    this.isLatestActivityModalVisible = true;
    this.deviceId = id;

    this.measureClient.getLatestActivityByDeviceId(id).subscribe(response => {
      this.specificDeviceActivity = response;

      if(response.dataValues != undefined) {
        response.dataValues.sort((a, b) => {
          if(a.created != undefined && b.created != undefined) {
            return new Date(b.created).getTime() - new Date(a.created).getTime();
          }
          return 0;
        });
      }

    });
  }

  generateNewApiKey() {
    const apiKeyRequest = new ApiKeyRequest();
    const expirationDate = new Date();
    const convertedNumber = Number(this.formData.controls.expirationDays.value ?? 30);

    expirationDate.setDate(expirationDate.getDate() + convertedNumber);

    apiKeyRequest.expirationDate = expirationDate;
    apiKeyRequest.name = this.formData.controls.name.value ?? "";

    this.deviceClient.updateApiKey(this.deviceId, apiKeyRequest).subscribe(response => {
      this.apiResponse = response;
      this.formData.reset();
    });
  }

  deleteDevice(id: string) {
    this.deviceClient.deleteDevice(id).subscribe(data => {
      this.loadDevices();
    })
  }
}

class ApiKeyFormControls {
  name: FormControl<string | null> = new FormControl('');
  expirationDays: FormControl<number| null> = new FormControl(30);
}