// angular import
import { Component } from '@angular/core';

// project import
import { SharedModule } from 'src/app/theme/shared/shared.module';

import { DeviceClient, DeviceRequest, DeviceResponse } from 'src/app/generated/autogenerated-client';
import { FormBuilder, FormGroup } from '@angular/forms';
@Component({
  selector: 'app-add-devices',
  standalone: true,
  imports: [SharedModule],
  providers: [DeviceClient],
  templateUrl: './add-devices.component.html',
  styleUrls: ['./add-devices.component.scss']
})
export default class AddDevicesComponent {

  deviceForm: FormGroup;

  constructor(private formBuilder:FormBuilder, private deviceClient:DeviceClient) {
    this.deviceForm = this.formBuilder.group({
      name: [''],
      macAddress: ['']
    })
  }

  CreateDevice(){
    let deviceRequest = new DeviceRequest()
    deviceRequest.name = this.deviceForm.value.name;
    deviceRequest.macAddress = this.deviceForm.value.macAddress;

    console.log(deviceRequest);

    this.deviceClient.createNewDevice(deviceRequest).subscribe();
  }
}
