apiVersion: batch/v1
kind: CronJob
metadata:
  name: hourly-acr-job-cron
  namespace: homeautomation
spec:
  schedule: "0 * * * *"  # Runs every hour
  timezone: "UTC"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: test-console-job
            image: tgclzdevacr.azurecr.io/tgc-ha-test-console:latest
          restartPolicy: OnFailure