import { Component } from '@angular/core';
import { ApexOptions, NgApexchartsModule } from 'ng-apexcharts';
import { MeasureClient } from 'src/app/generated/autogenerated-client';
import { SharedModule } from 'src/app/theme/shared/shared.module';

@Component({
  selector: 'app-temperature-summary',
  standalone: true,
  imports: [NgApexchartsModule, SharedModule],
  providers: [MeasureClient],
  templateUrl: './temperature-summary.component.html',
  styleUrl: './temperature-summary.component.scss'
})

export class TemperatureSummaryComponent {
  summaryChart: ApexOptions = {
    chart: {
      height: 350,
      type: 'area'
    },
    dataLabels: {
      enabled: false
    },
    series: [],
    stroke: {
      curve: 'smooth'
    },
    xaxis: {
      type: 'datetime',
      labels: {
        formatter: function (value: string) {
          const date = new Date(value);
          return date.toLocaleTimeString('en-DK'); // e.g., "11/05/2025"
        }
      }
    },
    yaxis: {
      labels: {
        formatter: (val: number) => val.toFixed(0) // 1 decimal place
      }
    },
    tooltip: {
      x: {
        format: 'dd/MM/yy HH:mm'
      },
      y: {
        formatter: (val: number) => val.toFixed(1) // 1 decimal place
      }
    }
  };

  constructor(private measureClient: MeasureClient) {
    const now = new Date(); // current date and time
    const twentyFourHoursAgo = new Date(now.getTime() - 24 * 60 * 60 * 1000); // subtract 24 hours
    this.plotMeasureData("temperature", twentyFourHoursAgo, now);
    this.plotMeasureData("humidity", twentyFourHoursAgo, now);
    this.plotMeasureData("co2", twentyFourHoursAgo, now);

  }

  private plotMeasureData(measureType:string, startTime:Date, endtime:Date):void {
    this.measureClient.getMeasuresByDate(measureType, startTime, endtime).subscribe(data => {

      let formattedResponse = data.dataValues?.map(data => {
        return {
          y: data.dataValue!,
          x: data.created!
        }
      });

      this.addToChartSeries(measureType, formattedResponse!)
    });
  }

  private addToChartSeries(seriesName:string, data:any):void {
    var some = [...this.summaryChart.series as [], {
      name: seriesName,
      data: data
    }];

    this.summaryChart.series = some;
  }
}
