import { Component } from '@angular/core';
import { DeviceClient, DeviceResponse } from 'src/app/generated/autogenerated-client';
import { SharedModule } from 'src/app/theme/shared/shared.module';

@Component({
  selector: 'app-device-table',
  imports: [SharedModule],
  providers: [DeviceClient],
  standalone: true,
  templateUrl: './device-table.component.html',
  styleUrl: './device-table.component.scss'
})
export class DeviceTableComponent {

  deviceData: DeviceResponse[] = [];

  constructor(private deviceClient:DeviceClient){

  }

  ngOnInit() {
    this.loadDevices();
  }

  loadDevices(){
    this.deviceClient.getAllDevices().subscribe(data => {
      this.deviceData = data;
    })
  }

  deleteDevice(id:string){
    console.log(id)
    this.deviceClient.deleteDevice(id).subscribe(data => {
      this.loadDevices();
    })
  }
}
