#https://forums.docker.com/t/install-docker-on-raspberry-pi-os-64-bit/115977

# version: '3'
# services:
#   homeassistant:
#     container_name: homeassistant
#     image: "ghcr.io/home-assistant/home-assistant:stable"
#     volumes:
#       - /opt/homeassistant/config:/config
#       - /etc/localtime:/etc/localtime:ro
#     restart: unless-stopped
#     privileged: true
#     network_mode: host


# sudo docker compose up -d

# port 8123

name: Run on Self-Hosted Agents

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, default]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - run: |
        echo "Hello, world!"
      name: "Test script"
    
    - run: |
        echo "Installing Ansible..."

        echo "Running: sudo apt update && sudo apt-get upgrade -y"
        sudo apt -y install software-properties-common

        echo "Running: sudo apt-add-repository --yes --update ppa:ansible/ansible"
        sudo apt-add-repository --yes --update ppa:ansible/ansible

        echo "Running: sudo apt -y install ansible"
        sudo apt -y install ansible

        echo "Finished installing!"
      name: "Test script"


        