#https://forums.docker.com/t/install-docker-on-raspberry-pi-os-64-bit/115977

version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /opt/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host


sudo docker compose up -d

port 8123