name: Deploy HomeAutomation

on: 
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy_application:
    environment: dev
    runs-on: [self-hosted, rasp01]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.HOMEAUTOMATION_DEV_CLIENT_ID }}
        tenant-id: ${{ secrets.HOMEAUTOMATION_DEV_TENANT_ID }}
        subscription-id: ${{ secrets.HOMEAUTOMATION_DEV_SUBSCRIPTION_ID }}
    
    - name: Fetch secret from Key Vault
      id: get_secret
      run: |
        secret=$(az keyvault secret show --vault-name "tgckvhadev" --name "certpassword" --query "value" -o tsv)
        echo "::add-mask::$secret"
        echo "certpassword=$secret" >> $GITHUB_ENV
    
    - run: |
        ansible-playbook ./ansible/roles/pi/playbooks/setup_nginx.yml --extra-vars "certname=asfwf kvname=tgckvhadev pw=$certpassword"
      name: "Configure Nginx"

    - run: |
        ansible-playbook ./ansible/roles/pi/playbooks/refresh_images.yml --extra-vars "acrUrl=tgclzdevacr appImageTag=latest apiImageTag=latest"
      name: "Run Ansible Playbook"