name: Deploy latest image to Raspberry

on: 
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy_application:
    name: Deploy newest images to Raspberries
    environment: dev
    runs-on: [self-hosted]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.HOMEAUTOMATION_DEV_CLIENT_ID }}
        tenant-id: ${{ secrets.HOMEAUTOMATION_DEV_TENANT_ID }}
        subscription-id: ${{ secrets.HOMEAUTOMATION_DEV_SUBSCRIPTION_ID }}

    - run: |
        ansible-playbook ./ansible/roles/pi/playbooks/refresh_images.yml --extra-vars "acrUrl=tgclzdevacr appImageTag=latest apiImageTag=latest"
      name: "Run Ansible Playbook"