name: Build TGC.DHT Docker Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build and deploy to ACR
    environment: dev
    env:
      image_name: tgc-ha-api
      project_name: TGC.HomeAutomation
      api_path: src/TGC.HomeAutomation/TGC.HomeAutomation.API/TGC.HomeAutomation.API.csproj
      acr_registry: tgclzdevacr.azurecr.io

    steps:
    - uses: actions/checkout@v3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - run: |
        docker --version

    - name: Restore dependencies
      run: dotnet restore $api_path

    - name: Build
      run: dotnet build $api_path --no-restore

    - name: 'Az CLI login'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.HOMEAUTOMATION_DEV_CLIENT_ID }}
        tenant-id: ${{ secrets.HOMEAUTOMATION_DEV_TENANT_ID }}
        subscription-id: ${{ secrets.HOMEAUTOMATION_DEV_SUBSCRIPTION_ID }}

    - run: |
        az acr login --name tgclzdevacr.azurecr.io
        cd src/TGC.HomeAutomation

        docker build . -t $acr_registry/$image_name:${{ github.sha }}
        docker build . -t $acr_registry/$image_name:latest

        docker push $acr_registry/$image_name:${{ github.sha }}
        docker push $acr_registry/$image_name:latest
      name: "Build and publish to ACR"

  deploy_raspberry:
    name: "Deploy to Raspberries"
    runs-on: [self-hosted]
    environment: dev
    needs: build_job
    env:
      image_name: tgc-ha-api
      acr_registry: tgclzdevacr.azurecr.io

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: 'Az CLI login'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.HOMEAUTOMATION_DEV_CLIENT_ID }}
        tenant-id: ${{ secrets.HOMEAUTOMATION_DEV_TENANT_ID }}
        subscription-id: ${{ secrets.HOMEAUTOMATION_DEV_SUBSCRIPTION_ID }}
    
    - run: |
        az acr login --name tgclzdevacr.azurecr.io

        docker pull $acr_registry/$image_name:latest
        docker run -d -p 8080:8080 $acr_registry/$image_name

      name: "Build and publish to ACR"