 # # # # # # # # # # # # # # # # # # # # # # # #
# REPLACE THE FOLLOWING VARIABLES AND ADJUST 
# - ENVIRONMENT_REFERENCE
# - CLIENT_ID_SECRET_REFERENCE
# - SUBSCRIPTION_ID_SECRET_REFERENCE
# - TENANT_ID_SECRET_REFERENCE
# - RESOURCE_GROUP_REFERENCE
# - STORAGE_ACCOUNT_REFERENCE
# - CONTAINER_NAME_REFERENCE
#
# # # # # # # # # # # # # # # # # # # # # # # # #

name: Deploy Infrastructure

on:
  push:
    branches: ["main"]
    paths:
    - 'terraform/**'
    - '.github/workflows/deploy_infrastructure.yml'
  pull_request:
    branches: ["main"]
    paths:
    - 'terraform/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build_job:
    runs-on: ubuntu-latest
    environment: dev #Should be changed, lol
    defaults:
      run:
        working-directory: ./terraform
    
    env:
      ARM_CLIENT_ID: "${{ secrets.HOMEAUTOMATION_DEV_CLIENT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.HOMEAUTOMATION_DEV_SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.HOMEAUTOMATION_DEV_TENANT_ID }}"
      ARM_USE_AZUREAD: true

    steps:
    - uses: actions/checkout@v3

    - name: Install Terraform
      run: bash "${{ github.workspace }}/.github/scripts/install_terraform.sh" 

    - name: Terraform Fmt
      run: terraform fmt -check

    - name: Terraform Init
      run: |
        terraform init \
        -backend-config=resource_group_name="rg-landingzone-shared-dev-westeurope" \
        -backend-config=storage_account_name="${{ secrets.HOMEAUTOMATION_DEV_TFSTATE_STORAGE_ACCOUNT_NAME }}" \
        -backend-config=container_name="${{ secrets.HOMEAUTOMATION_DEV_TFSTATE_STORAGE_CONTAINER_NAME }}" \
        -backend-config=key="KEY_NAME"
        
    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan -input=false -var="tenant_id=${{ secrets.HOMEAUTOMATION_DEV_TENANT_ID }}" -var-file="envs/dev.tfvars" -out=tfplan #UPDATE VARS file

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan