name: Generate SSL-Certificates

on: 
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  create_secret:
    environment: dev
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2