name: Health-check self-hosted runners

on:
  schedule:
    # Runs every day at 2:00 AM UTC
    - cron: '0 0,6,12,18 * * *'
  push:
    branches:
    - main
    paths:
    - '.github/workflows/health_check.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ rasp01, rasp02 ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - run: |
        echo "I am alive"
      name: "Check alive"

    - run: |
        ansible-playbook ./ansible/roles/pi/playbooks/update_runner.yml
      name: "Update apt-packages"