name: Health-check self-hosted runners

on:
  schedule:
    # Runs every day at 2:00 AM UTC
    - cron: '0 0,6,12,18 * * *'
  push:
    branches:
    - main
    paths:
    - '.github/workflows/health_check.yml'
  workflow_dispatch:

jobs:
    build:
        strategy:
            matrix:
                runner: [rasp01]
        runs-on: self-hosted

        steps:
        - run: |
            echo "I am alive"
          name: "Check alive"

        - run: |
            echo "Runnning apt update..."
            # sudo apt update
            echo "apt update completed."

            echo "Running apt-get upgrade -y... This may take some time."
            # sudo apt-get upgrade -y
            echo "apt-get upgrade -y completed."

            echo "Running sudo apt autoremove..."
            # sudo apt autoremove -y
            echo "apt autoremove completed."
          name: "Check alive"